// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get_bio.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_bio_default = defineTool({
  name: "get_bio",
  title: "Get Jordan Lander's bio",
  description: "Return a short professional bio for Jordan Lander, including current role, background, and areas of expertise.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const bio = {
      name: "Jordan Lander",
      tagline: "Education Leader & Technology Innovator",
      currentRole: "Supervisor of Special Education, Northwest Tri-County IU5",
      summary: "Forward-thinking education administrator with 15+ years of experience designing inclusive STEAM curricula, leading change initiatives, and empowering teams through technology and creativity.",
      leadershipHighlights: [
        "Redesigned virtual learning program, saving over $800K in outplacement costs",
        "Led development of digital tools streamlining compliance and collaboration for K\u201312 staff",
        "Implemented strategies boosting reading and math performance on standardized assessments",
        "Built partnerships with families and organizations to support inclusive learning environments"
      ],
      expertise: {
        educationalLeadership: [
          "Curriculum Design",
          "STEAM Integration",
          "Data-Driven Instruction",
          "Special Education",
          "Virtual Learning"
        ],
        teamDevelopment: [
          "Professional Learning",
          "Coaching & Mentoring",
          "Change Management",
          "PBIS Implementation",
          "Inclusive Practices"
        ],
        technologyAndInnovation: [
          "LMS Platforms",
          "Digital Tools",
          "Web Development",
          "Ed Tech Integration",
          "Project Management"
        ]
      },
      website: "https://jordanlander.com"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(bio, null, 2) }],
      structuredContent: bio
    };
  }
});

// src/lib/mcp/tools/get_experience.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_experience_default = defineTool2({
  name: "get_experience",
  title: "Get professional experience",
  description: "Return Jordan Lander's professional experience timeline, including titles, organizations, dates, and highlights for each role.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const experience = [
      {
        title: "Supervisor of Special Education",
        organization: "Northwest Tri-County IU5",
        period: "Jul 2025 \u2013 Present",
        highlights: [
          "Lead strategic vision & daily operations for special education across multiple districts",
          "Manage IEP development, compliance with IDEA/Pennsylvania regs, and transition planning",
          "Supervise & mentor certified teachers & paraprofessionals in student-centered culture",
          "Design & deliver professional learning on PBIS, inclusive practices, and data-driven instruction"
        ]
      },
      {
        title: "Assistant Principal & Cyber Liaison",
        organization: "Corry Area SD",
        period: "Jan 2022 \u2013 Jun 2025",
        highlights: [
          "Redesigned Corry Virtual Academy, cutting cyber placement costs by $800K+ annually",
          "Supervised curriculum development and professional learning for virtual instruction",
          "Led data-driven instructional improvements across K\u201312",
          "Launched digital platforms for district-wide collaboration and compliance tracking"
        ]
      },
      {
        title: "Science Teacher",
        organization: "Erie's Public Schools",
        period: "Aug 2016 \u2013 Jan 2022",
        highlights: [
          "Led advanced science and CTE programs while mentoring colleagues in technology integration",
          "Consulted on curriculum design and building-wide instructional initiatives",
          "Recognized for innovative instruction and student engagement"
        ]
      }
    ];
    return {
      content: [{ type: "text", text: JSON.stringify(experience, null, 2) }],
      structuredContent: { experience }
    };
  }
});

// src/lib/mcp/tools/get_books.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_books_default = defineTool3({
  name: "get_books",
  title: "Get published books",
  description: "Return Jordan Lander's published books available on Amazon, with titles, subtitles, prices, and purchase links.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: () => {
    const books = [
      {
        title: "Circle Meditation",
        subtitle: "31 Days of Coloring & Reflection",
        author: "Jordan Charles Lander",
        price: "$9.99",
        amazon: "https://www.amazon.com/dp/B0H4BJRH7C"
      },
      {
        title: "Emerson the Super Squirrel",
        subtitle: "A PBIS Coloring Adventure for Positive Behavior",
        author: "Mr. Jordan Lander",
        price: "$7.99",
        amazon: "https://www.amazon.com/dp/B0F5Q5WVWM"
      },
      {
        title: "A Strong Woman",
        subtitle: "Coloring Book",
        author: "Jordan Charles Lander",
        price: "$12.99",
        amazon: "https://www.amazon.com/dp/B0DJRDPTJJ"
      },
      {
        title: "Passive-Aggressive Office Notes",
        subtitle: "The Funny and Relatable Adult Coloring Book",
        author: "Jordan Charles Lander",
        price: "$7.99",
        amazon: "https://www.amazon.com/dp/B0C52216QY"
      }
    ];
    const authorPage = "https://www.amazon.com/stores/Jordan-Charles-Lander/author/B0C5TYWMDD";
    return {
      content: [
        { type: "text", text: JSON.stringify({ books, authorPage }, null, 2) }
      ],
      structuredContent: { books, authorPage }
    };
  }
});

// src/lib/mcp/tools/get_news.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_news_default = defineTool4({
  name: "get_news",
  title: "Get news & recognition",
  description: "Return media features and community recognition articles mentioning Jordan Lander, with dates, summaries, and source URLs.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: () => {
    const news = [
      {
        title: "Students honor valor in verse",
        date: "2023-11-08",
        summary: "Supported a Veterans Day poetry tribute blending service learning with student creativity.",
        url: "https://www.thecorryjournal.com/news/article_601bf1ca-7e40-11ee-8e9f-0f5b8a2de589.html"
      },
      {
        title: "Heroes bring early Christmas for Corry, UC kids",
        date: "2024-12-20",
        summary: "Collaborated with community partners to deliver magical early-Christmas experiences for students.",
        url: "https://www.thecorryjournal.com/news/article_837a2826-be4a-11ef-b99c-dffd8f302ff5.html"
      },
      {
        title: "Santa Fund campaign underway",
        date: "2023-12-09",
        summary: "Supported the Santa Fund drive, providing festive support to dozens of local families in need.",
        url: "https://www.thecorryjournal.com/news/article_ff57e93e-95f5-11ee-a773-f336ac1d073e.html"
      },
      {
        title: "Acclaimed children's author visits schools",
        date: "2024-03-07",
        summary: "Coordinated with library staff to curate live author visits that inspired a renewed passion for reading.",
        url: "https://www.thecorryjournal.com/news/article_8c495c80-dc03-11ee-8b6b-07e7c75a2175.html"
      },
      {
        title: "CAIS supports city K\u20119 initiative",
        date: "2022-12-08",
        summary: "Worked with law-enforcement liaisons on a K\u20119 initiative strengthening safety partnerships and student engagement.",
        url: "https://www.thecorryjournal.com/news/article_9d2e9196-7714-11ed-8804-bfd14463a803.html"
      },
      {
        title: "CAIS finalist in 'How Cool is Your School?'",
        date: "2022-11-01",
        summary: "Led a student-driven media team producing award-winning project videos, fueling a culture of innovation.",
        url: "https://www.thecorryjournal.com/news/article_904f14d2-59fa-11ed-89a9-2fb400f148c8.html"
      }
    ];
    return {
      content: [{ type: "text", text: JSON.stringify(news, null, 2) }],
      structuredContent: { news }
    };
  }
});

// src/lib/mcp/tools/get_web_services.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_web_services_default = defineTool5({
  name: "get_web_services",
  title: "Get One Weekend Websites info",
  description: "Return information about One Weekend Websites \u2014 Jordan Lander's small-business web development service, including offering, pricing, and URL.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: () => {
    const service = {
      name: "One Weekend Websites",
      url: "https://www.oneweekendwebsites.com/",
      description: "Clean, mobile-first websites for small businesses. A fast, professional one-page site delivered by Monday.",
      pricing: "$499 flat rate",
      turnaround: "By Monday",
      focus: "Small business one-page websites"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(service, null, 2) }],
      structuredContent: service
    };
  }
});

// src/lib/mcp/tools/get_contact.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_contact_default = defineTool6({
  name: "get_contact",
  title: "Get contact & social links",
  description: "Return ways to contact or connect with Jordan Lander online, including website and public profiles.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const contact = {
      website: "https://jordanlander.com",
      businessSite: "https://www.oneweekendwebsites.com/",
      amazonAuthor: "https://www.amazon.com/stores/Jordan-Charles-Lander/author/B0C5TYWMDD"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(contact, null, 2) }],
      structuredContent: contact
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "jordan-lander-portfolio",
  title: "Jordan Lander Portfolio",
  version: "0.1.0",
  instructions: "Read-only tools for Jordan Lander's professional portfolio. Use `get_bio` for a summary, `get_experience` for the work history timeline, `get_books` for published titles on Amazon, `get_news` for media features and recognition, `get_web_services` for the One Weekend Websites offering, and `get_contact` for online links. All data is public.",
  tools: [get_bio_default, get_experience_default, get_books_default, get_news_default, get_web_services_default, get_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
